openapi: "3.0.2"
info:
  title: "Sample API"
  version: "2.0.0"
servers:  
  - url: "http://localhost:8080"
    description: "ローカル開発環境"
paths:
  /users:
    get:
      summary: "全ユーザーを取得"
      responses:
        '200':
          description: "ユーザーリストの取得に成功"
  paths:
  /user/create:
    post:
      summary: ユーザ情報作成API
      description: |
        ユーザ情報を作成します。ユーザの名前情報をリクエストで受け取り、ユーザIDと認証用のトークンを生成しデータベースへ保存します。tokenは以降の他のAPIコール時にヘッダに設定をします。
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
